version: "3.9"

services:
  microlearn:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    expose:
      - 5432
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
