-- CreateEnum
CREATE TYPE "PREFERRED_APPLICANT_GENDER" AS ENUM ('MALE', 'FEMALE', 'ALL');

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "preferredApplicantGender" "PREFERRED_APPLICANT_GENDER" NOT NULL DEFAULT 'ALL';
